// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $examples_id_ from "./routes/examples/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $AnimatedMesh from "./islands/AnimatedMesh.tsx";
import * as $BasicCube from "./islands/BasicCube.tsx";
import * as $LightingShadows from "./islands/LightingShadows.tsx";
import * as $Tesseract from "./islands/Tesseract.tsx";
import * as $Torus from "./islands/Torus.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/examples/[id].tsx": $examples_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AnimatedMesh.tsx": $AnimatedMesh,
    "./islands/BasicCube.tsx": $BasicCube,
    "./islands/LightingShadows.tsx": $LightingShadows,
    "./islands/Tesseract.tsx": $Tesseract,
    "./islands/Torus.tsx": $Torus,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
